name: Publish Extension

on:
  push:
    tags: 
    - '*'


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - run: npm install
      - uses: lannonbr/vsce-action@master
        with:
          args: "publish"
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}