name: Publish Extension

on:
  push:
    tags: 
    - '*'


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: lannonbr/vsce-action@510e61c5e9e6f33c0418ec5ff5fd36b1ced61e85 # master
        with:
          args: "publish"
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}